<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title><?= $this->title ?></title>
    <link rel="stylesheet" href="<?= utils::getCss('reset') ?>">
    <link rel="stylesheet" href="<?= utils::getCss('master') ?>">
    <script src="<?= utils::getJS('jquery') ?>"></script>
</head>
<body id="" onload="">
<div class="mainWrapper">
    <div class="topGreySquare"></div>
    <img src="<?= utils::getImage('dotmvc.png') ?>">
    <hr>
    <div class="content">
        <?= $this->content; ?>
    </div>
    <hr>
    <div class="footer">
        All Rights Reserved To Avihay Menahem ©
    </div>
</div>
</body>
</html>